package com.mylog.mapper;

import com.mylog.domain.LogsAct;

import java.util.List;

public interface LogsActMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_act
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String act);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_act
     *
     * @mbg.generated
     */
    int insert(LogsAct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_act
     *
     * @mbg.generated
     */
    LogsAct selectByPrimaryKey(String act);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_act
     *
     * @mbg.generated
     */
    List<LogsAct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logs_act
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LogsAct record);
}